version: '3'

services:
  uploadApk:
    image: node:14
    volumes:
    - "./:/opt/www"
    ports:
      - "3001:3000"
    privileged: true
    working_dir: /opt/www/
    depends_on:
      - graphQL
    restart: always
    networks:
      - default
    command:
      - bash
      - -c
      - |
          yarn
          ls -ahl
          node -v
          node uploadIndex.js

  graphQL:
    image: node:14
    volumes:
      - "./:/opt/www"
    ports:
      - "3002:5000"
    privileged: true
    working_dir: /opt/www/
    restart: always
    networks:
      - default
    command:
      - bash
      - -c
      - |
        yarn
        ls -ahl
        node -v
        pwd
        node index.js

networks:
  default:
